fix non exiting exit 1

diff --git a/tmpl b/tmpl
--- a/tmpl
+++ b/tmpl
@@ -126,8 +126,8 @@ case "$subcommand" in
             esac
         done
         shift $((OPTIND -1))
-        [ "$#" -gt 2 ] && ( echo "Invalid number of arguments." 1>&2; usage; exit 1 )
-        [ -z "$1" ] && ( echo "Required argument 'SOURCE' not provided." 1>&2; usage; exit 1 )
+        [ "$#" -gt 2 ] && ( echo "Invalid number of arguments." 1>&2; usage ) && exit 1
+        [ -z "$1" ] && ( echo "Required argument 'SOURCE' not provided." 1>&2; usage ) && exit 1
 
         add_source="$1"
         [ -z "$2" ] || add_dest="$2"
@@ -135,8 +135,8 @@ case "$subcommand" in
         ;;
 
     fetch )
-        [ "$#" -gt 2 ] && ( echo "Invalid number of arguments" 1>&2; usage; exit 1 )
-        [ -z "$1" ] && ( echo "Required argument 'TEMPLATE' not provided." 1>&2; usage; exit 1 )
+        [ "$#" -gt 2 ] && ( echo "Invalid number of arguments" 1>&2; usage ) && exit 1
+        [ -z "$1" ] && ( echo "Required argument 'TEMPLATE' not provided." 1>&2; usage ) && exit 1
 
         fetch_template="$1"
         [ -z "$2" ] || fetch_dest="$2"
